### PR TITLE
Added requirements.txt

### PR DESCRIPTION
**Pull request by aayushbisen**
Added requirements.txt file that contains all the dependencies for the project. It will help future contributors to easily setup the project. ✔

### CODE REVIEW

**Comment by aayushbisen** [comment]
@sunn-e Kindly review.

**Comment by sunn-e** [comment]
Add the requirements to README.md too. That will be better.

**Comment by aayushbisen** [comment]
Added.

**Comment by sunn-e** [comment]
cool. Merging. Thanks for the changes.

**Pull request merged**
