### PR TITLE
Patch : Fixed issue 14 and 18

### PR DESCRIPTION
**Pull request by Rits1272**
Changed the variable name and fixed the bug.

### CODE REVIEW

**Comment by Rits1272** [comment]
Can someone help fix this issue?I am unable to solve it.

**Comment by sunn-e** [comment]
By any chance you changed files names ?

**Comment by Rits1272** [comment]
I think all error are solved now. Please review!

**Comment by sunn-e** [comment]
Hey @Rits1272, which ide are you using. Why don't you create a fresh fork and redo the changes as per your wish. I will be happy to help you. Just mention me once you are done, cool?

**Pull request closed without merging**
