### PR TITLE
Scrapped wikiquote

### PR DESCRIPTION
**Pull request by rakaar**
can get quote by author and quote of the day.

### CODE REVIEW

**Comment by rakaar** [comment]
#12 scrapping from wikiquote by author and quote of the day

**Comment by yashagarwal1999** [comment]
Is this   issue still open?? CAn i work on this??

**Comment by sunn-e** [comment]
@yashagarwal1999 , yes.

**Comment by sunn-e** [comment]
better submit from new branch.

**Comment by sunn-e** [comment]
@rakaar , congrats. Sorry for the delay.

**Pull request merged**
