### PR TITLE
Scrap from quotery

### PR DESCRIPTION
**Pull request by DestroyerAlpha**
#7 
A scrapper for https://www.quotery.com/
The text files are to match the input with the authors and categories from the website.
The text files have been scrapped by me separately.

### CODE REVIEW

**Review by akshatkarani — COMMENTED** [review]
Indentation is not uniform throughout.

**Comment by DestroyerAlpha** [comment]
Made necessary changes.

**Comment by akshatkarani** [comment]
The text files will increase the size of the package and we cannot do this for every site. There must be some other way.
ping @svp19

**Comment by svp19** [comment]
Agreed @akshatkarani. I explored the implementation of [pyjokes](https://pypi.org/project/pyjokes/) #sourceofinspiration and they too render jokes as text from .py files. Explains why they have only a few.

An alternative would be to set up a server to store all quotes and return them through an API call defined in the package. However, if you do this, then the package won't work offline.

Maybe you could mix both approaches, providing an offline version that is limited and an optional online version that works well.

**Comment by yugaljain1999** [comment]
> Agreed @akshatkarani. I explored the implementation of [pyjokes](https://pypi.org/project/pyjokes/) #sourceofinspiration and they too render jokes as text from .py files. Explains why they have only a few.
> 
> An alternative would be to set up a server to store all quotes and return them through an API call defined in the package. However, if you do this, then the package won't work offline.
> 
> Maybe you could mix both approaches, providing an offline version that is limited and an optional online version that works well.

We can create offline package with the help of storing all authors and categories in csv file by making own dataset and then can get quotes according to author names and categories through csv file

**Pull request merged**
