### PR TITLE
Update all irrelevant variable names correctly

### LINKED ISSUE #14: brainyquote.py: Change variable name
In many places `list` is used as a variable name. Change variable names to something more appropriate.

### PR DESCRIPTION
**Pull request by parammittal16**
Fixes #14 @akshatkarani @sunn-e plz review.

### CODE REVIEW

**Review by sunn-e — APPROVED** [review]
I'm not even mad. :p Good job. CTRL+H helped you a lot it seems. I'm approving this. Thanks  @parammittal16 Congrats on your merge acceptance.

**Comment by parammittal16** [comment]
@sunn-e thanks a lot :)

**Comment by sunn-e** [comment]
@parammittal16  you need 3+ PR to receive goodies. Hope you do that before month ends. 
Choose any from [here](https://github.com/oss2019/pyquotes/issues) or suggest something you want to do.

**Comment by parammittal16** [comment]
@sunn-e on the site it is written min 3 PR to be merged :) to receive goodies.
https://oss2019.github.io/SoI.html
Am I correct?

**Comment by sunn-e** [comment]
@parammittal16 , yes.

**Pull request merged**
